import { useEffect, useState } from "react";
import { createMasterDataRepository, type MasterDataRepository } from "../../data/repositories/master-data-repository";
import type { MasterDataSnapshot } from "../../domain/types";
import { MasterDataEditor } from "./MasterDataEditor";
import { StandardTimeEditor } from "./StandardTimeEditor";
import { UserEditor, type NewUser } from "./UserEditor";

async function invokeAdminCreateUser(input: NewUser) { const client: any = (await import("../../data/supabase")).getSupabaseClient(); const { error } = await client.functions.invoke("admin-create-user", { body: input }); if (error) throw new Error(error.message || "user_creation_failed"); }
export function AdminPage({ repository, createUser = invokeAdminCreateUser }: { repository?: MasterDataRepository; createUser?: (input: NewUser) => Promise<unknown> }) { const [snapshot, setSnapshot] = useState<MasterDataSnapshot | null>(null); const [error, setError] = useState(""); const getRepository = () => repository ?? createMasterDataRepository(); const refresh = async () => { try { setError(""); setSnapshot(await getRepository().listMasterData()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load master data."); } }; useEffect(() => { void refresh(); }, [repository]); if (error) return <main><h1>Administration</h1><p>Admin workspace</p><p role="alert">{error}</p><button onClick={() => void refresh()}>Retry</button></main>; if (!snapshot) return <main><h1>Administration</h1><p>Admin workspace</p><p role="status">Loading master data…</p></main>; return <main><h1>Administration</h1><p>Admin workspace</p><MasterDataEditor snapshot={snapshot} createModel={async (input) => { await getRepository().createModel(input); await refresh(); }} deactivateDowntimeReason={async (id) => { await getRepository().deactivateDowntimeReason(id); await refresh(); }} /><StandardTimeEditor snapshot={snapshot} save={async (input) => { const saved = await getRepository().saveStandardTime(input); await refresh(); return saved; }} /><UserEditor createUser={createUser} /></main>; }
