project_id = "smd-process-control"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[db.migrations]
enabled = true

[realtime]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
enable_anonymous_sign_ins = false

[storage]
enabled = true
