import { useMemo, useRef, useState } from "react";
import { previewProductionMetrics, productionEntrySchema, validateDowntime } from "../../domain/validation";
import type { MasterDataSnapshot, ProductionEntryDraft } from "../../domain/types";
import type { ProductionRepository } from "../../data/repositories/production-repository";
import { DowntimeEditor } from "./DowntimeEditor";

const blank: ProductionEntryDraft = { productionDate: "", shiftId: "", timeSlotId: "", lineId: "", modelId: "", processId: "", inputQty: 0, actualQty: 0, okQty: 0, ngQty: 0, note: "", downtime: [] };
export function ProductionEntryForm({ masterData, repository, onConflict }: { masterData: MasterDataSnapshot; repository: ProductionRepository; onConflict(draft: ProductionEntryDraft): Promise<void> }) {
  const [draft, setDraft] = useState(blank); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const submitting = useRef(false);
  const preview = useMemo(() => draft.productionDate ? previewProductionMetrics(draft, masterData) : null, [draft, masterData]);
  const valid = productionEntrySchema.safeParse(draft).success && preview?.plannedSeconds !== null && validateDowntime(draft.downtime, preview?.plannedSeconds ?? 0).ok;
  const set = <K extends keyof ProductionEntryDraft>(key: K, value: ProductionEntryDraft[K]) => setDraft((old) => ({ ...old, [key]: value }));
  const submit = async () => { if (!valid || submitting.current) return; submitting.current = true; setSaving(true); setMessage(""); try { await repository.saveProductionRecord(draft, 0); setMessage("Saved"); setDraft(blank); } catch (error: any) { if (error?.code === "40001") { setMessage("다른 사용자가 수정했습니다"); await onConflict(draft); } else if (error?.code === "42501") setMessage("수정 권한이 없습니다"); else setMessage("저장에 실패했습니다"); } finally { submitting.current = false; setSaving(false); } };
  const number = (key: "inputQty" | "actualQty" | "okQty" | "ngQty", label: string) => <label>{label}<input aria-label={label} type="number" min="0" value={draft[key]} onChange={(e) => set(key, e.target.value === "" ? Number.NaN : Number(e.target.value))} /></label>;
  return <form onSubmit={(e) => { e.preventDefault(); void submit(); }}><label>Production date<input aria-label="Production date" type="date" value={draft.productionDate} onChange={(e) => set("productionDate", e.target.value)} /></label><label>Shift<select aria-label="Shift" value={draft.shiftId} onChange={(e) => { set("shiftId", e.target.value); set("timeSlotId", ""); }}><option value="">Select</option>{masterData.shifts.filter((x) => x.active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Time slot<select aria-label="Time slot" value={draft.timeSlotId} onChange={(e) => set("timeSlotId", e.target.value)}><option value="">Select</option>{masterData.timeSlots.filter((x) => x.shiftId === draft.shiftId).map((x) => <option key={x.id} value={x.id}>{x.code}</option>)}</select></label>{([['Line','lineId',masterData.lines],['Model','modelId',masterData.models],['Process','processId',masterData.processes]] as const).map(([label,key,items]) => <label key={key}>{label}<select aria-label={label} value={draft[key]} onChange={(e) => set(key, e.target.value)}><option value="">Select</option>{items.filter((x) => x.active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}{number("inputQty", "Input")}{number("actualQty", "Actual")}{number("okQty", "OK")}{number("ngQty", "NG")}<label>Note<textarea aria-label="Note" value={draft.note} onChange={(e) => set("note", e.target.value)} /></label><DowntimeEditor rows={draft.downtime} reasons={masterData.downtimeReasons.filter((x) => x.active)} onChange={(rows) => set("downtime", rows)} />{preview && <section aria-live="polite"><p>{preview.standardTime ? `Standard time: ${preview.standardTime.secondsPerUnit} sec/unit` : "Standard time: unavailable"}</p><p>Yield: {preview.yieldResult.status === "ok" ? preview.yieldResult.value : "—"}</p><p>Utilization: {preview.utilizationResult.status === "ok" ? preview.utilizationResult.value : "—"}</p></section>}{message && <p role="alert">{message}</p>}<button type="submit" disabled={!valid || saving}>{saving ? "Saving" : "Save"}</button></form>;
}
